### ISSUE TITLE
How swift compatible Alibaba oss？could you give me a demo？

### ISSUE THREAD

**Issue by RayOsLei** [gholt/ring#35]

**Comment by gholt** [comment]
I'm not 100% sure I understand the question, but if you're asking if this ring library is compatible with OpenStack Swift, is it **not** at all compatible. It is also not compatible with Alibaba OSS, but to be honest, I just now looked up what that is. Hope this helps!

**Comment by RayOsLei** [comment]
@gholt  thank you!!!,I just know the compatibility between swift and Alibaba oss,and a http interface of oss ,which how to access swift? could you give me a demo?

**Comment by gholt** [comment]
I have no idea, sorry. And nope, no demos. This project is not Swift nor Alibaba related at all.
